### ISSUE TITLE
report pandoc version

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/sessioninfo#41]

**Comment by gaborcsardi** [comment]
@cderv should we try to find pandoc by ourselves, e.g. via `RSTUDIO_PANDOC` and `Sys.which("pandoc")`? Or call `rmarkdown::find_pandoc()`. What if rmarkdown is not installed?

**Comment by cderv** [comment]
I think it would be best to rely on `rmarkdown::find_pandoc()` as this way the reported version will be the one used by **rmarkdown**. If you do it by yourself, there is no certainty that you will report the version that will be used: 

* Either because you don't use the same algorithm to select (**rmarkdown** reports latest version found in different paths). 
* Either because a user could change the version used itself using `rmarkdown::find_pandoc()` and you won't know about that unless you call the function. 


FWIW, `xfun::session_info()` as an internal mechanism to report external tools when other packages are available. This works by having `xfun::session_info()` calls an internal function of such packages: 
* Code from **xfun**: https://github.com/yihui/xfun/blob/0c2ee10630b40ce813b203375521c9a6a0f8c408/R/session.R#L72-L74
* Example in **rmarkdown** with `rmarkdown:::xfun_session_info()` to report pandoc: https://github.com/rstudio/rmarkdown/blob/71ae8292f809f2b4b20cfcba001d62d996e1d25e/R/util.R#L525-L527
* Example in **blogdown** with `blogdown:::xfun_session_info()` to report Hugo: https://github.com/rstudio/blogdown/blob/c496d860799fc0d731f31a73163261087afc1162/R/utils.R#L987-L989

Also if you only need the version of Pandoc, this would `rmarkdown:::pandoc_version()`. Internally, this calls `find_pandoc()` with default arg and report only the version. `rmarkdown::find_pandoc()` would allow to have also the path of the version used by rmardkown. But both are good anyway. 

> What if rmarkdown is not installed?

I think that if rmarkdown is installed it would be best to report this version. If not installed, it is possible that the R user is using another tool than rmarkdown and in this case I guess `Sys.which("pandoc")` is the right one to use. RSTUDIO_PANDOC binary should be really use only by **rmarkdown** I think. 


Overall, I believe it is useful to report Pandoc version in `session_info()` to help with **rmarkdown** related debugging or snapshot of current system state. I would report it when **rmarkdown** is among the package found by `package_info()`.

**Comment by gaborcsardi** [comment]
Thanks, sounds good all good!

> RSTUDIO_PANDOC binary should be really use only by rmarkdown I think.

Well, rcmdcheck puts `RSTUDIO_PANDOC` on the path now, and others might just pick it up as well: https://github.com/search?q=org%3Acran+RSTUDIO_PANDOC&type=code

I will report if it is from `RSTUDIO_PANDOC` or not.

> I would report it when rmarkdown is among the package found by package_info()

rmarkdown is usually a suggested package, and thus not picked up by `package_info()`. Maybe this should change, I'll think about it.

**Comment by cderv** [comment]
>  rcmdcheck puts RSTUDIO_PANDOC on the path now, 

Oh ok ! I didn't know that (or didn't remember). I don't know if there could be issue with the way rmarkdown is using it. Not the place to discuss but if you have a system pandoc version above `RSTUDIO_PANDOC`, the former will be used. Vignette would be built with this one but rcmdcheck would check with another one. 

There should not be much difference though. I find it hard to know / manage pandoc version reliably sometimes.

> I will report if it is from RSTUDIO_PANDOC or not.

For a recent work I have done regarding new `pandoc_*()` functions to install and manage pandoc versions, I have made the distinction between : RStudio Pandoc (from `RSTUDIO_PANDOC`), System Pandoc (in PATH), User installed Pandoc (not in PATH). Maybe you can report this kind of status with the version ? 

However, if you report the path to pandoc binary and the version, it should be clear which version it is for the user, especially if it is in RStudio directory structure.
